### PR TITLE
Center

### PR DESCRIPTION
**Pull request by drewtu2**
Hi Xiangyu,

I believe I have everything working now. Please let me know if there are any issues. 

Thanks,
Andrew

### CODE REVIEW

**Comment by yiskylee** [comment]
@drewtu2 , could you make another pull from upstream?

**Comment by drewtu2** [comment]
Hi Xiangyu,

I pulled from upstream and fixed the merge conflict. Please let me know if there are any other issues.

Andrew

**Comment by yiskylee** [comment]
Hey @drewtu2 , your branch doesn't compile when I run "make" in cpp/build on my system. Could you take a look at it?

**Comment by drewtu2** [comment]
Okay I fixed the issue. it seems I deleted an extra bracket by mistake when fixing the original merge issues from the pull from upstream.

**Comment by yiskylee** [comment]
@drewtu2 , I got a warning that says: warning: control reaches end of non-void function [-Wreturn-type]
   }

Could you take a look and fix it? And also please make another pull from develop as I have done some fix since your last pull request. Thanks!

**Comment by drewtu2** [comment]
Fixed!

**Comment by yiskylee** [comment]
Please perform a "make check" and fix the google code style errors.

**Comment by yiskylee** [comment]
@drewtu2 , Just a friendly reminder that this is still unsolved.

**Comment by drewtu2** [comment]
Hi Xiangyu,

I updated the center function to what you recommended. 

"make check" wasn't flagging a capital variable name as wrong in the code style - are there any other major violations that make check won't catch so I can update the other branches accordingly?

**Comment by yiskylee** [comment]
The cpplint.py also doesn't check the indentations - as long as the number of spaces in the indentations are even. 
Could you pull from upstream develop again? Please make sure that when you do a pull request, avoid having the message of "This branch has conflicts that must be resolved" by doing a pull from upstream.

**Pull request merged**
