### PR TITLE
Matrix subtract

### PR DESCRIPTION
**Pull request by ademosthene**

### CODE REVIEW

**Comment by yiskylee** [comment]
@ademosthene , this looks great! The only change that I would like you to make would be to rename MatrixSubtract_test.cc to matrix_subtract_test.cc as it follows the google code style.
Thanks.

**Comment by yiskylee** [comment]
Make sure to pull from upstream develop before fixing anything.

**Comment by ademosthene** [comment]
matrix-scalar subtract is pushed

**Comment by yiskylee** [comment]
Looks good!

**Pull request merged**
