### PR TITLE
Dot Product

### PR DESCRIPTION
**Pull request by lesliechase**

### CODE REVIEW

**Comment by yiskylee** [comment]
Could you add the test for dot product as well?

**Comment by lesliechase** [comment]
Yes I am writing that right now. I just wanted to commit the dot product implementation first. I will send a message in Campfire to let you know when I have added my test.

**Comment by yiskylee** [comment]
This looks great! Could you make it a typed test case? You can learn about typed test at https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md (search for "Typed Test" and just read that section)

**Comment by yiskylee** [comment]
It seems that the dot product doesn't pass the tests:
[----------] 3 tests from DotProductTest/1, where TypeParam = float
[ RUN      ] DotProductTest/1.DotProductFunctionality
/home/xiangyu/git_project/NICE/cpp/test/cpu_operations_test/DotProduct_test.cc:65: Failure
      Expected: this->result
      Which is: 0.702763
To be equal to: correct
      Which is: 0.702763
[  FAILED  ] DotProductTest/1.DotProductFunctionality, where TypeParam = float (0 ms)

Try use EXPECT_NEAR(val1, val2, abs_error) to allow an accuracy error, you can learn about how EXPECT_NEAR and ASSERT_NEAR work at:
https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md

**Comment by lesliechase** [comment]
Should be all set now! It passed all the tests on my end. Thanks for pointing that out.

**Pull request merged**
